name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/checkout@v2
      with:
        repository: 'GNOME/libxml2'
        ref: 'v2.9.10'
      
    - uses: actions/checkout@v2
      with:
        repository: 'curl/curl'
        ref: 'curl-7_71_1'
      
    - name: set dependency directory
      run: |
        mkdir dependency
        CUR_DIR=`pwd`
        export DEP_INSTALL_DIR=${CUR_DIR}/dependency
        ls
      
    - name: compile libxml2
      run: |
        cd libxml2
        ./autogen.sh
        ./configure --prefix=${DEP_INSTALL_DIR}
        make
        make install
        cd ..
      
    - name: compile curl
      run: |
        cd curl
        chmod u+x configure
        ./configure --prefix=${DEP_INSTALL_DIR}
        make
        make install
        cd ..
    
    - name: make
      run: make CUSTOM_INSTALL_DIR=${DEP_INSTALL_DIR}
