name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/checkout@v2
      with:
        repository: GNOME/libxml2
        ref: v2.9.10
        path: libxml2
      
    - uses: actions/checkout@v2
      with:
        repository: curl/curl
        ref: curl-7_71_1
        path: curl
      
    - name: set dependency directory
      run: |
        mkdir dependency
        ls
      
    - name: compile curl
      run: |
        cd curl
        CUR_DIR=`pwd`
        ./buildconf
        ./configure --prefix=${CUR_DIR}/dependency
        make
        make install
        cd ..
    
    - name: make
      run: |
        CUR_DIR=`pwd`
        make CUSTOM_INSTALL_DIR=${CUR_DIR}/dependency
